version: '3'

services:
  redis:
    image: redis:6.2.5
    command: redis-server --requirepass ${REDIS_PASS}
    container_name: redis_easychat
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
  easychat:
    build: .
    image: easychat:1.0
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - /home/bruno/Projetos/easychat/.env:/usr/src/app/.env
    container_name: easychat
    environment:
      TZ: "America/Sao_Paulo"
      HOST_IP: ${HOST_IP}
      JVM_MEM_OPTS: "-Xms4g -Xmx4g"